title: CSS Bristol
email: webmaster@cssbristol.co.uk
description: CSS is the University of Bristol Computer Science Society. We exist to represent, support and entertain all members of the Computer Science department.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.cssbristol.co.uk" # the base hostname & protocol for your site
twitter_username: cssbristol
github_username: cssbristol
timezone: Etc/UTC
future: true

# Build settings
markdown: kramdown

collections:
  tutorials:
    output: true
    permalink: /tutorials/:path/
  jobs:
    output: true
    permalink: /jobs/:path/
  events:
    output: true
    permalink: /events/:path/

plugins:
  - jekyll-redirect-from

exclude:
  - _tutorials/template
  - _jobs/template
  - _events/template
  - _posts/template
  - vendor
